# Application setting
spring.profiles.active=mongo

# Server
server.host=0.0.0.0
server.port=8080

# MongoDB
mongodb.uri=${MONGODB_URI:mongodb://mongodb:27017/quizbot}
mongodb.database=${MONGODB_DATABASE:quiz_bot}

# Kafka
kafka.bootstrap-servers=localhost:9092
kafka.topic.form-tasks=form-solving-requests


# Telegram Bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:MyQuizBot}
telegram.webhook.path=/webhook/telegram

# GigaChat LLM
gigachat.api-key=${GIGACHAT_API_KEY:}
gigachat.api-url=https://gigachat.devices.sberbank.ru/api/v1

# Admin Auth
admin.jwt-secret=${JWT_SECRET:}

